name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build React app
        run: npm run build

      - name: Debug Environment Variables
        run: |
          echo "SERVER_USER: $SERVER_USER"
          echo "SERVER_IP: $SERVER_IP"


      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ubuntu
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << EOF
          if [ ! -d "/home/ubuntu/doppler-demo" ]; then
            git clone https://github.com/Iheanacho-ai/doppler-demo.git /home/ubuntu/doppler-demo
          fi
          cd /home/ubuntu/doppler-demo
          git pull origin main
          npm ci --omit=dev
          EOF

      - name: Transfer Build Artifacts
        run: |
          scp -o StrictHostKeyChecking=no -i private_key.pem -r .next $SERVER_USER@$SERVER_IP:/home/ubuntu/doppler-demo/

      - name: Restart PM2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP << EOF
          cd /home/ubuntu/doppler-demo
          sudo npm install -g pm2
          pm2 restart doppler-demo || pm2 start npm --name 'doppler-demo' -- start
          pm2 save
          EOF
