name: Deploy React App to AWS EC2

on:
  push:
    branches:
      - main # Or your main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_USER: ubuntu
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i private_key.pem" ./build/ $SERVER_USER@$SERVER_IP:/home/ubuntu/doppler-demo

          ssh -o StrictHostKeyChecking=no -i private_key.pem $SERVER_USER@$SERVER_IP "
            cd /home/ubuntu/doppler-demo &&
            npm install --omit=dev &&   # Install production dependencies only
            pm2 delete doppler-demo || true
            pm2 start npm --name 'doppler-demo' -- start